/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeleteTestOutputDto } from '../models/delete-test-output-dto';
import { ReadTestOutputDto } from '../models/read-test-output-dto';
import { UpdateTestOutputDto } from '../models/update-test-output-dto';
import { WriteTestOutputDto } from '../models/write-test-output-dto';
export interface AllTestOutputDto {
  deleteTest?: DeleteTestOutputDto;
  readTest?: ReadTestOutputDto;
  updateTest?: UpdateTestOutputDto;
  writeTest?: WriteTestOutputDto;
}
