/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NodePath {
  nameCount?: number;
  parent?: NodePath;
  pathType?: 'LEGACY' | 'JSON_PATH' | 'JSON_POINTER' | 'URI_REFERENCE';
}
