/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParishSummaryDto } from '../models/parish-summary-dto';
export interface ParishionerDto {
  birthDate?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  parish?: ParishSummaryDto;
}
