/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParishSummaryDto } from '../models/parish-summary-dto';
export interface PriestDto {
  firstName?: string;
  id?: number;
  lastName?: string;
  ordinationDate?: string;
  parishes?: Array<ParishSummaryDto>;
}
