/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AbsoluteIri } from '../models/absolute-iri';
import { NodePath } from '../models/node-path';
export interface SchemaLocation {
  absoluteIri?: AbsoluteIri;
  fragment?: NodePath;
}
