/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddPriestCommand } from '../../models/add-priest-command';
import { PriestSummaryDto } from '../../models/priest-summary-dto';

export interface AddPriest1$Params {
  parishId: number;
      body: AddPriestCommand
}

export function addPriest1(http: HttpClient, rootUrl: string, params: AddPriest1$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, addPriest1.PATH, 'post');
  if (params) {
    rb.path('parishId', params.parishId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PriestSummaryDto>;
    })
  );
}

addPriest1.PATH = '/api/parish/{parishId}/priests';
