/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddParishionerCommand } from '../../models/add-parishioner-command';
import { ParishionerSummaryDto } from '../../models/parishioner-summary-dto';

export interface AddParishioner1$Params {
  parishId: number;
      body: AddParishionerCommand
}

export function addParishioner1(http: HttpClient, rootUrl: string, params: AddParishioner1$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, addParishioner1.PATH, 'post');
  if (params) {
    rb.path('parishId', params.parishId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishionerSummaryDto>;
    })
  );
}

addParishioner1.PATH = '/api/parish/{parishId}/parishioners';
