/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateParishCommand } from '../../models/create-parish-command';
import { ParishDto } from '../../models/parish-dto';

export interface CreateParish$Params {
      body: CreateParishCommand
}

export function createParish(http: HttpClient, rootUrl: string, params: CreateParish$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDto>> {
  const rb = new RequestBuilder(rootUrl, createParish.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishDto>;
    })
  );
}

createParish.PATH = '/api/parish';
