/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishDto } from '../../models/parish-dto';

export interface DeleteParish$Params {
  parishId: number;
}

export function deleteParish(http: HttpClient, rootUrl: string, params: DeleteParish$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDto>> {
  const rb = new RequestBuilder(rootUrl, deleteParish.PATH, 'delete');
  if (params) {
    rb.path('parishId', params.parishId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishDto>;
    })
  );
}

deleteParish.PATH = '/api/parish/{parishId}';
