/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishSummaryDto } from '../../models/parish-summary-dto';

export interface GetAllParishesSummary$Params {
}

export function getAllParishesSummary(http: HttpClient, rootUrl: string, params?: GetAllParishesSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishSummaryDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllParishesSummary.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ParishSummaryDto>>;
    })
  );
}

getAllParishesSummary.PATH = '/api/parish/summary';
