/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PriestSummaryDto } from '../../models/priest-summary-dto';

export interface GetPriests1$Params {
  parishId: number;
}

export function getPriests1(http: HttpClient, rootUrl: string, params: GetPriests1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PriestSummaryDto>>> {
  const rb = new RequestBuilder(rootUrl, getPriests1.PATH, 'get');
  if (params) {
    rb.path('parishId', params.parishId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PriestSummaryDto>>;
    })
  );
}

getPriests1.PATH = '/api/parish/{parishId}/priests';
