/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishionerSummaryDto } from '../../models/parishioner-summary-dto';

export interface RemoveParishioner1$Params {
  parishId: number;
  parishionerId: number;
}

export function removeParishioner1(http: HttpClient, rootUrl: string, params: RemoveParishioner1$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, removeParishioner1.PATH, 'delete');
  if (params) {
    rb.path('parishId', params.parishId, {});
    rb.path('parishionerId', params.parishionerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishionerSummaryDto>;
    })
  );
}

removeParishioner1.PATH = '/api/parish/{parishId}/priests/{parishionerId}';
