/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishDto } from '../../models/parish-dto';
import { UpdateParishCommand } from '../../models/update-parish-command';

export interface UpdateParish$Params {
  parishId: number;
      body: UpdateParishCommand
}

export function updateParish(http: HttpClient, rootUrl: string, params: UpdateParish$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDto>> {
  const rb = new RequestBuilder(rootUrl, updateParish.PATH, 'put');
  if (params) {
    rb.path('parishId', params.parishId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishDto>;
    })
  );
}

updateParish.PATH = '/api/parish/{parishId}';
