/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddPriestEmbeddedCommand } from '../../models/add-priest-embedded-command';
import { PriestEmbeddedDto } from '../../models/priest-embedded-dto';

export interface AddPriest$Params {
  parishDocumentId: string;
      body: AddPriestEmbeddedCommand
}

export function addPriest(http: HttpClient, rootUrl: string, params: AddPriest$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestEmbeddedDto>> {
  const rb = new RequestBuilder(rootUrl, addPriest.PATH, 'post');
  if (params) {
    rb.path('parishDocumentId', params.parishDocumentId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PriestEmbeddedDto>;
    })
  );
}

addPriest.PATH = '/api/parishDocument/{parishDocumentId}/priests';
