/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddParishionerEmbeddedCommand } from '../../models/add-parishioner-embedded-command';
import { ParishionerEmbeddedDto } from '../../models/parishioner-embedded-dto';

export interface AddParishioner$Params {
  parishDocumentId: string;
      body: AddParishionerEmbeddedCommand
}

export function addParishioner(http: HttpClient, rootUrl: string, params: AddParishioner$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerEmbeddedDto>> {
  const rb = new RequestBuilder(rootUrl, addParishioner.PATH, 'post');
  if (params) {
    rb.path('parishDocumentId', params.parishDocumentId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishionerEmbeddedDto>;
    })
  );
}

addParishioner.PATH = '/api/parishDocument/{parishDocumentId}/parishioners';
