/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishDocumentDto } from '../../models/parish-document-dto';

export interface GetAllParishDocuments$Params {
}

export function getAllParishDocuments(http: HttpClient, rootUrl: string, params?: GetAllParishDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishDocumentDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllParishDocuments.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ParishDocumentDto>>;
    })
  );
}

getAllParishDocuments.PATH = '/api/parishDocument';
