/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishionerEmbeddedDto } from '../../models/parishioner-embedded-dto';

export interface GetParishioners$Params {
  parishDocumentId: string;
}

export function getParishioners(http: HttpClient, rootUrl: string, params: GetParishioners$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishionerEmbeddedDto>>> {
  const rb = new RequestBuilder(rootUrl, getParishioners.PATH, 'get');
  if (params) {
    rb.path('parishDocumentId', params.parishDocumentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ParishionerEmbeddedDto>>;
    })
  );
}

getParishioners.PATH = '/api/parishDocument/{parishDocumentId}/parishioners';
