/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PriestEmbeddedDto } from '../../models/priest-embedded-dto';

export interface GetPriests$Params {
  parishDocumentId: string;
}

export function getPriests(http: HttpClient, rootUrl: string, params: GetPriests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PriestEmbeddedDto>>> {
  const rb = new RequestBuilder(rootUrl, getPriests.PATH, 'get');
  if (params) {
    rb.path('parishDocumentId', params.parishDocumentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PriestEmbeddedDto>>;
    })
  );
}

getPriests.PATH = '/api/parishDocument/{parishDocumentId}/priests';
