/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishDocumentDto } from '../../models/parish-document-dto';

export interface GetParishDocumentById$Params {
  parishDocumentId: string;
}

export function getParishDocumentById(http: HttpClient, rootUrl: string, params: GetParishDocumentById$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDocumentDto>> {
  const rb = new RequestBuilder(rootUrl, getParishDocumentById.PATH, 'get');
  if (params) {
    rb.path('parishDocumentId', params.parishDocumentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishDocumentDto>;
    })
  );
}

getParishDocumentById.PATH = '/api/parishDocument/{parishDocumentId}';
