/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RemovePriest$Params {
  parishDocumentId: string;
  priestEmbeddedId: string;
}

export function removePriest(http: HttpClient, rootUrl: string, params: RemovePriest$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, removePriest.PATH, 'delete');
  if (params) {
    rb.path('parishDocumentId', params.parishDocumentId, {});
    rb.path('priestEmbeddedId', params.priestEmbeddedId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

removePriest.PATH = '/api/parishDocument/{parishDocumentId}/priests/{priestEmbeddedId}';
