/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishDocumentDto } from '../../models/parish-document-dto';

export interface UpdateParishDocument$Params {
      body: ParishDocumentDto
}

export function updateParishDocument(http: HttpClient, rootUrl: string, params: UpdateParishDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDocumentDto>> {
  const rb = new RequestBuilder(rootUrl, updateParishDocument.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishDocumentDto>;
    })
  );
}

updateParishDocument.PATH = '/api/parishDocument';
