/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PriestEmbeddedDto } from '../../models/priest-embedded-dto';
import { UpdatePriestEmbeddedCommand } from '../../models/update-priest-embedded-command';

export interface UpdatePriest1$Params {
  parishDocumentId: string;
  priestEmbeddedId: string;
      body: UpdatePriestEmbeddedCommand
}

export function updatePriest1(http: HttpClient, rootUrl: string, params: UpdatePriest1$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestEmbeddedDto>> {
  const rb = new RequestBuilder(rootUrl, updatePriest1.PATH, 'put');
  if (params) {
    rb.path('parishDocumentId', params.parishDocumentId, {});
    rb.path('priestEmbeddedId', params.priestEmbeddedId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PriestEmbeddedDto>;
    })
  );
}

updatePriest1.PATH = '/api/parishDocument/{parishDocumentId}/priests/{priestEmbeddedId}';
