/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishionerEmbeddedDto } from '../../models/parishioner-embedded-dto';
import { UpdateParishionerEmbeddedCommand } from '../../models/update-parishioner-embedded-command';

export interface UpdateParishioner1$Params {
  parishDocumentId: string;
  parishionerEmbeddedId: string;
      body: UpdateParishionerEmbeddedCommand
}

export function updateParishioner1(http: HttpClient, rootUrl: string, params: UpdateParishioner1$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerEmbeddedDto>> {
  const rb = new RequestBuilder(rootUrl, updateParishioner1.PATH, 'put');
  if (params) {
    rb.path('parishDocumentId', params.parishDocumentId, {});
    rb.path('parishionerEmbeddedId', params.parishionerEmbeddedId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishionerEmbeddedDto>;
    })
  );
}

updateParishioner1.PATH = '/api/parishDocument/{parishDocumentId}/parishioners/{parishionerEmbeddedId}';
