/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateParishionerCommand } from '../../models/create-parishioner-command';
import { ParishionerDto } from '../../models/parishioner-dto';

export interface CreateParishioner$Params {
      body: CreateParishionerCommand
}

export function createParishioner(http: HttpClient, rootUrl: string, params: CreateParishioner$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerDto>> {
  const rb = new RequestBuilder(rootUrl, createParishioner.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishionerDto>;
    })
  );
}

createParishioner.PATH = '/api/parishioner';
