/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishionerDto } from '../../models/parishioner-dto';

export interface GetParishionerById$Params {
  parishionerId: number;
}

export function getParishionerById(http: HttpClient, rootUrl: string, params: GetParishionerById$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerDto>> {
  const rb = new RequestBuilder(rootUrl, getParishionerById.PATH, 'get');
  if (params) {
    rb.path('parishionerId', params.parishionerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishionerDto>;
    })
  );
}

getParishionerById.PATH = '/api/parishioner/{parishionerId}';
