/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParishionerDto } from '../../models/parishioner-dto';
import { UpdateParishionerCommand } from '../../models/update-parishioner-command';

export interface UpdateParishioner$Params {
  parishionerId: number;
      body: UpdateParishionerCommand
}

export function updateParishioner(http: HttpClient, rootUrl: string, params: UpdateParishioner$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerDto>> {
  const rb = new RequestBuilder(rootUrl, updateParishioner.PATH, 'put');
  if (params) {
    rb.path('parishionerId', params.parishionerId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParishionerDto>;
    })
  );
}

updateParishioner.PATH = '/api/parishioner/{parishionerId}';
