/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePriestCommand } from '../../models/create-priest-command';
import { PriestDto } from '../../models/priest-dto';

export interface CreatePriest$Params {
      body: CreatePriestCommand
}

export function createPriest(http: HttpClient, rootUrl: string, params: CreatePriest$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestDto>> {
  const rb = new RequestBuilder(rootUrl, createPriest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PriestDto>;
    })
  );
}

createPriest.PATH = '/api/priest';
