/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PriestDto } from '../../models/priest-dto';

export interface DeletePriest$Params {
  priestId: number;
}

export function deletePriest(http: HttpClient, rootUrl: string, params: DeletePriest$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestDto>> {
  const rb = new RequestBuilder(rootUrl, deletePriest.PATH, 'delete');
  if (params) {
    rb.path('priestId', params.priestId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PriestDto>;
    })
  );
}

deletePriest.PATH = '/api/priest/{priestId}';
