/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addParishioner1 } from '../fn/parish/add-parishioner-1';
import { AddParishioner1$Params } from '../fn/parish/add-parishioner-1';
import { addPriest1 } from '../fn/parish/add-priest-1';
import { AddPriest1$Params } from '../fn/parish/add-priest-1';
import { createParish } from '../fn/parish/create-parish';
import { CreateParish$Params } from '../fn/parish/create-parish';
import { deleteParish } from '../fn/parish/delete-parish';
import { DeleteParish$Params } from '../fn/parish/delete-parish';
import { getAllParishes } from '../fn/parish/get-all-parishes';
import { GetAllParishes$Params } from '../fn/parish/get-all-parishes';
import { getAllParishesSummary } from '../fn/parish/get-all-parishes-summary';
import { GetAllParishesSummary$Params } from '../fn/parish/get-all-parishes-summary';
import { getParishById } from '../fn/parish/get-parish-by-id';
import { GetParishById$Params } from '../fn/parish/get-parish-by-id';
import { getParishioners1 } from '../fn/parish/get-parishioners-1';
import { GetParishioners1$Params } from '../fn/parish/get-parishioners-1';
import { getPriests1 } from '../fn/parish/get-priests-1';
import { GetPriests1$Params } from '../fn/parish/get-priests-1';
import { ParishDto } from '../models/parish-dto';
import { ParishionerSummaryDto } from '../models/parishioner-summary-dto';
import { ParishSummaryDto } from '../models/parish-summary-dto';
import { PriestSummaryDto } from '../models/priest-summary-dto';
import { removeParishioner1 } from '../fn/parish/remove-parishioner-1';
import { RemoveParishioner1$Params } from '../fn/parish/remove-parishioner-1';
import { removePriest1 } from '../fn/parish/remove-priest-1';
import { RemovePriest1$Params } from '../fn/parish/remove-priest-1';
import { updateParish } from '../fn/parish/update-parish';
import { UpdateParish$Params } from '../fn/parish/update-parish';

@Injectable({ providedIn: 'root' })
export class ParishService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getParishById()` */
  static readonly GetParishByIdPath = '/api/parish/{parishId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getParishById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishById$Response(params: GetParishById$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDto>> {
    const obs = getParishById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getParishById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishById(params: GetParishById$Params, context?: HttpContext): Observable<ParishDto> {
    const resp = this.getParishById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishDto>): ParishDto => r.body)
    );
  }

  /** Path part for operation `updateParish()` */
  static readonly UpdateParishPath = '/api/parish/{parishId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateParish()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateParish$Response(params: UpdateParish$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDto>> {
    const obs = updateParish(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateParish$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateParish(params: UpdateParish$Params, context?: HttpContext): Observable<ParishDto> {
    const resp = this.updateParish$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishDto>): ParishDto => r.body)
    );
  }

  /** Path part for operation `deleteParish()` */
  static readonly DeleteParishPath = '/api/parish/{parishId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteParish()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteParish$Response(params: DeleteParish$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDto>> {
    const obs = deleteParish(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteParish$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteParish(params: DeleteParish$Params, context?: HttpContext): Observable<ParishDto> {
    const resp = this.deleteParish$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishDto>): ParishDto => r.body)
    );
  }

  /** Path part for operation `getAllParishes()` */
  static readonly GetAllParishesPath = '/api/parish';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllParishes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishes$Response(params?: GetAllParishes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishDto>>> {
    const obs = getAllParishes(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllParishes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishes(params?: GetAllParishes$Params, context?: HttpContext): Observable<Array<ParishDto>> {
    const resp = this.getAllParishes$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ParishDto>>): Array<ParishDto> => r.body)
    );
  }

  /** Path part for operation `createParish()` */
  static readonly CreateParishPath = '/api/parish';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createParish()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createParish$Response(params: CreateParish$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDto>> {
    const obs = createParish(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createParish$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createParish(params: CreateParish$Params, context?: HttpContext): Observable<ParishDto> {
    const resp = this.createParish$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishDto>): ParishDto => r.body)
    );
  }

  /** Path part for operation `getPriests1()` */
  static readonly GetPriests1Path = '/api/parish/{parishId}/priests';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPriests1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPriests1$Response(params: GetPriests1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PriestSummaryDto>>> {
    const obs = getPriests1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPriests1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPriests1(params: GetPriests1$Params, context?: HttpContext): Observable<Array<PriestSummaryDto>> {
    const resp = this.getPriests1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<PriestSummaryDto>>): Array<PriestSummaryDto> => r.body)
    );
  }

  /** Path part for operation `addPriest1()` */
  static readonly AddPriest1Path = '/api/parish/{parishId}/priests';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addPriest1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addPriest1$Response(params: AddPriest1$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestSummaryDto>> {
    const obs = addPriest1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addPriest1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addPriest1(params: AddPriest1$Params, context?: HttpContext): Observable<PriestSummaryDto> {
    const resp = this.addPriest1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PriestSummaryDto>): PriestSummaryDto => r.body)
    );
  }

  /** Path part for operation `getParishioners1()` */
  static readonly GetParishioners1Path = '/api/parish/{parishId}/parishioners';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getParishioners1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishioners1$Response(params: GetParishioners1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishionerSummaryDto>>> {
    const obs = getParishioners1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getParishioners1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishioners1(params: GetParishioners1$Params, context?: HttpContext): Observable<Array<ParishionerSummaryDto>> {
    const resp = this.getParishioners1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ParishionerSummaryDto>>): Array<ParishionerSummaryDto> => r.body)
    );
  }

  /** Path part for operation `addParishioner1()` */
  static readonly AddParishioner1Path = '/api/parish/{parishId}/parishioners';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addParishioner1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addParishioner1$Response(params: AddParishioner1$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerSummaryDto>> {
    const obs = addParishioner1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addParishioner1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addParishioner1(params: AddParishioner1$Params, context?: HttpContext): Observable<ParishionerSummaryDto> {
    const resp = this.addParishioner1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishionerSummaryDto>): ParishionerSummaryDto => r.body)
    );
  }

  /** Path part for operation `getAllParishesSummary()` */
  static readonly GetAllParishesSummaryPath = '/api/parish/summary';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllParishesSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishesSummary$Response(params?: GetAllParishesSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishSummaryDto>>> {
    const obs = getAllParishesSummary(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllParishesSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishesSummary(params?: GetAllParishesSummary$Params, context?: HttpContext): Observable<Array<ParishSummaryDto>> {
    const resp = this.getAllParishesSummary$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ParishSummaryDto>>): Array<ParishSummaryDto> => r.body)
    );
  }

  /** Path part for operation `removePriest1()` */
  static readonly RemovePriest1Path = '/api/parish/{parishId}/priests/{priestId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removePriest1()` instead.
   *
   * This method doesn't expect any request body.
   */
  removePriest1$Response(params: RemovePriest1$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestSummaryDto>> {
    const obs = removePriest1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removePriest1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removePriest1(params: RemovePriest1$Params, context?: HttpContext): Observable<PriestSummaryDto> {
    const resp = this.removePriest1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PriestSummaryDto>): PriestSummaryDto => r.body)
    );
  }

  /** Path part for operation `removeParishioner1()` */
  static readonly RemoveParishioner1Path = '/api/parish/{parishId}/priests/{parishionerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeParishioner1()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeParishioner1$Response(params: RemoveParishioner1$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerSummaryDto>> {
    const obs = removeParishioner1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeParishioner1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeParishioner1(params: RemoveParishioner1$Params, context?: HttpContext): Observable<ParishionerSummaryDto> {
    const resp = this.removeParishioner1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishionerSummaryDto>): ParishionerSummaryDto => r.body)
    );
  }

}
