/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addParishioner } from '../fn/parish-document/add-parishioner';
import { AddParishioner$Params } from '../fn/parish-document/add-parishioner';
import { addPriest } from '../fn/parish-document/add-priest';
import { AddPriest$Params } from '../fn/parish-document/add-priest';
import { createParishDocument } from '../fn/parish-document/create-parish-document';
import { CreateParishDocument$Params } from '../fn/parish-document/create-parish-document';
import { deleteParishDocument } from '../fn/parish-document/delete-parish-document';
import { DeleteParishDocument$Params } from '../fn/parish-document/delete-parish-document';
import { getAllParishDocuments } from '../fn/parish-document/get-all-parish-documents';
import { GetAllParishDocuments$Params } from '../fn/parish-document/get-all-parish-documents';
import { getParishDocumentById } from '../fn/parish-document/get-parish-document-by-id';
import { GetParishDocumentById$Params } from '../fn/parish-document/get-parish-document-by-id';
import { getParishionerById1 } from '../fn/parish-document/get-parishioner-by-id-1';
import { GetParishionerById1$Params } from '../fn/parish-document/get-parishioner-by-id-1';
import { getParishioners } from '../fn/parish-document/get-parishioners';
import { GetParishioners$Params } from '../fn/parish-document/get-parishioners';
import { getPriestById1 } from '../fn/parish-document/get-priest-by-id-1';
import { GetPriestById1$Params } from '../fn/parish-document/get-priest-by-id-1';
import { getPriests } from '../fn/parish-document/get-priests';
import { GetPriests$Params } from '../fn/parish-document/get-priests';
import { ParishDocumentDto } from '../models/parish-document-dto';
import { ParishionerEmbeddedDto } from '../models/parishioner-embedded-dto';
import { PriestEmbeddedDto } from '../models/priest-embedded-dto';
import { removeParishioner } from '../fn/parish-document/remove-parishioner';
import { RemoveParishioner$Params } from '../fn/parish-document/remove-parishioner';
import { removePriest } from '../fn/parish-document/remove-priest';
import { RemovePriest$Params } from '../fn/parish-document/remove-priest';
import { updateParishDocument } from '../fn/parish-document/update-parish-document';
import { UpdateParishDocument$Params } from '../fn/parish-document/update-parish-document';
import { updateParishioner1 } from '../fn/parish-document/update-parishioner-1';
import { UpdateParishioner1$Params } from '../fn/parish-document/update-parishioner-1';
import { updatePriest1 } from '../fn/parish-document/update-priest-1';
import { UpdatePriest1$Params } from '../fn/parish-document/update-priest-1';

@Injectable({ providedIn: 'root' })
export class ParishDocumentService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllParishDocuments()` */
  static readonly GetAllParishDocumentsPath = '/api/parishDocument';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllParishDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishDocuments$Response(params?: GetAllParishDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishDocumentDto>>> {
    const obs = getAllParishDocuments(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllParishDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishDocuments(params?: GetAllParishDocuments$Params, context?: HttpContext): Observable<Array<ParishDocumentDto>> {
    const resp = this.getAllParishDocuments$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ParishDocumentDto>>): Array<ParishDocumentDto> => r.body)
    );
  }

  /** Path part for operation `updateParishDocument()` */
  static readonly UpdateParishDocumentPath = '/api/parishDocument';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateParishDocument()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateParishDocument$Response(params: UpdateParishDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDocumentDto>> {
    const obs = updateParishDocument(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateParishDocument$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateParishDocument(params: UpdateParishDocument$Params, context?: HttpContext): Observable<ParishDocumentDto> {
    const resp = this.updateParishDocument$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishDocumentDto>): ParishDocumentDto => r.body)
    );
  }

  /** Path part for operation `createParishDocument()` */
  static readonly CreateParishDocumentPath = '/api/parishDocument';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createParishDocument()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createParishDocument$Response(params: CreateParishDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDocumentDto>> {
    const obs = createParishDocument(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createParishDocument$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createParishDocument(params: CreateParishDocument$Params, context?: HttpContext): Observable<ParishDocumentDto> {
    const resp = this.createParishDocument$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishDocumentDto>): ParishDocumentDto => r.body)
    );
  }

  /** Path part for operation `getPriestById1()` */
  static readonly GetPriestById1Path = '/api/parishDocument/{parishDocumentId}/priests/{priestEmbeddedId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPriestById1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPriestById1$Response(params: GetPriestById1$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestEmbeddedDto>> {
    const obs = getPriestById1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPriestById1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPriestById1(params: GetPriestById1$Params, context?: HttpContext): Observable<PriestEmbeddedDto> {
    const resp = this.getPriestById1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PriestEmbeddedDto>): PriestEmbeddedDto => r.body)
    );
  }

  /** Path part for operation `updatePriest1()` */
  static readonly UpdatePriest1Path = '/api/parishDocument/{parishDocumentId}/priests/{priestEmbeddedId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePriest1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePriest1$Response(params: UpdatePriest1$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestEmbeddedDto>> {
    const obs = updatePriest1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePriest1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePriest1(params: UpdatePriest1$Params, context?: HttpContext): Observable<PriestEmbeddedDto> {
    const resp = this.updatePriest1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PriestEmbeddedDto>): PriestEmbeddedDto => r.body)
    );
  }

  /** Path part for operation `removePriest()` */
  static readonly RemovePriestPath = '/api/parishDocument/{parishDocumentId}/priests/{priestEmbeddedId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removePriest()` instead.
   *
   * This method doesn't expect any request body.
   */
  removePriest$Response(params: RemovePriest$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = removePriest(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removePriest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removePriest(params: RemovePriest$Params, context?: HttpContext): Observable<void> {
    const resp = this.removePriest$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getParishionerById1()` */
  static readonly GetParishionerById1Path = '/api/parishDocument/{parishDocumentId}/parishioners/{parishionerEmbeddedId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getParishionerById1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishionerById1$Response(params: GetParishionerById1$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerEmbeddedDto>> {
    const obs = getParishionerById1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getParishionerById1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishionerById1(params: GetParishionerById1$Params, context?: HttpContext): Observable<ParishionerEmbeddedDto> {
    const resp = this.getParishionerById1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishionerEmbeddedDto>): ParishionerEmbeddedDto => r.body)
    );
  }

  /** Path part for operation `updateParishioner1()` */
  static readonly UpdateParishioner1Path = '/api/parishDocument/{parishDocumentId}/parishioners/{parishionerEmbeddedId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateParishioner1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateParishioner1$Response(params: UpdateParishioner1$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerEmbeddedDto>> {
    const obs = updateParishioner1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateParishioner1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateParishioner1(params: UpdateParishioner1$Params, context?: HttpContext): Observable<ParishionerEmbeddedDto> {
    const resp = this.updateParishioner1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishionerEmbeddedDto>): ParishionerEmbeddedDto => r.body)
    );
  }

  /** Path part for operation `removeParishioner()` */
  static readonly RemoveParishionerPath = '/api/parishDocument/{parishDocumentId}/parishioners/{parishionerEmbeddedId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeParishioner()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeParishioner$Response(params: RemoveParishioner$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = removeParishioner(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeParishioner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeParishioner(params: RemoveParishioner$Params, context?: HttpContext): Observable<void> {
    const resp = this.removeParishioner$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPriests()` */
  static readonly GetPriestsPath = '/api/parishDocument/{parishDocumentId}/priests';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPriests()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPriests$Response(params: GetPriests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PriestEmbeddedDto>>> {
    const obs = getPriests(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPriests$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPriests(params: GetPriests$Params, context?: HttpContext): Observable<Array<PriestEmbeddedDto>> {
    const resp = this.getPriests$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<PriestEmbeddedDto>>): Array<PriestEmbeddedDto> => r.body)
    );
  }

  /** Path part for operation `addPriest()` */
  static readonly AddPriestPath = '/api/parishDocument/{parishDocumentId}/priests';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addPriest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addPriest$Response(params: AddPriest$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestEmbeddedDto>> {
    const obs = addPriest(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addPriest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addPriest(params: AddPriest$Params, context?: HttpContext): Observable<PriestEmbeddedDto> {
    const resp = this.addPriest$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PriestEmbeddedDto>): PriestEmbeddedDto => r.body)
    );
  }

  /** Path part for operation `getParishioners()` */
  static readonly GetParishionersPath = '/api/parishDocument/{parishDocumentId}/parishioners';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getParishioners()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishioners$Response(params: GetParishioners$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishionerEmbeddedDto>>> {
    const obs = getParishioners(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getParishioners$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishioners(params: GetParishioners$Params, context?: HttpContext): Observable<Array<ParishionerEmbeddedDto>> {
    const resp = this.getParishioners$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ParishionerEmbeddedDto>>): Array<ParishionerEmbeddedDto> => r.body)
    );
  }

  /** Path part for operation `addParishioner()` */
  static readonly AddParishionerPath = '/api/parishDocument/{parishDocumentId}/parishioners';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addParishioner()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addParishioner$Response(params: AddParishioner$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerEmbeddedDto>> {
    const obs = addParishioner(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addParishioner$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addParishioner(params: AddParishioner$Params, context?: HttpContext): Observable<ParishionerEmbeddedDto> {
    const resp = this.addParishioner$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishionerEmbeddedDto>): ParishionerEmbeddedDto => r.body)
    );
  }

  /** Path part for operation `getParishDocumentById()` */
  static readonly GetParishDocumentByIdPath = '/api/parishDocument/{parishDocumentId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getParishDocumentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishDocumentById$Response(params: GetParishDocumentById$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDocumentDto>> {
    const obs = getParishDocumentById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getParishDocumentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishDocumentById(params: GetParishDocumentById$Params, context?: HttpContext): Observable<ParishDocumentDto> {
    const resp = this.getParishDocumentById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishDocumentDto>): ParishDocumentDto => r.body)
    );
  }

  /** Path part for operation `deleteParishDocument()` */
  static readonly DeleteParishDocumentPath = '/api/parishDocument/{parishDocumentId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteParishDocument()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteParishDocument$Response(params: DeleteParishDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishDocumentDto>> {
    const obs = deleteParishDocument(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteParishDocument$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteParishDocument(params: DeleteParishDocument$Params, context?: HttpContext): Observable<ParishDocumentDto> {
    const resp = this.deleteParishDocument$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishDocumentDto>): ParishDocumentDto => r.body)
    );
  }

}
