/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createParishioner } from '../fn/parishioner/create-parishioner';
import { CreateParishioner$Params } from '../fn/parishioner/create-parishioner';
import { deleteParishioner } from '../fn/parishioner/delete-parishioner';
import { DeleteParishioner$Params } from '../fn/parishioner/delete-parishioner';
import { getAllParishioners } from '../fn/parishioner/get-all-parishioners';
import { GetAllParishioners$Params } from '../fn/parishioner/get-all-parishioners';
import { getAllParishionersSummary } from '../fn/parishioner/get-all-parishioners-summary';
import { GetAllParishionersSummary$Params } from '../fn/parishioner/get-all-parishioners-summary';
import { getParishionerById } from '../fn/parishioner/get-parishioner-by-id';
import { GetParishionerById$Params } from '../fn/parishioner/get-parishioner-by-id';
import { ParishionerDto } from '../models/parishioner-dto';
import { ParishionerSummaryDto } from '../models/parishioner-summary-dto';
import { updateParishioner } from '../fn/parishioner/update-parishioner';
import { UpdateParishioner$Params } from '../fn/parishioner/update-parishioner';

@Injectable({ providedIn: 'root' })
export class ParishionerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getParishionerById()` */
  static readonly GetParishionerByIdPath = '/api/parishioner/{parishionerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getParishionerById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishionerById$Response(params: GetParishionerById$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerDto>> {
    const obs = getParishionerById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getParishionerById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getParishionerById(params: GetParishionerById$Params, context?: HttpContext): Observable<ParishionerDto> {
    const resp = this.getParishionerById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishionerDto>): ParishionerDto => r.body)
    );
  }

  /** Path part for operation `updateParishioner()` */
  static readonly UpdateParishionerPath = '/api/parishioner/{parishionerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateParishioner()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateParishioner$Response(params: UpdateParishioner$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerDto>> {
    const obs = updateParishioner(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateParishioner$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateParishioner(params: UpdateParishioner$Params, context?: HttpContext): Observable<ParishionerDto> {
    const resp = this.updateParishioner$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishionerDto>): ParishionerDto => r.body)
    );
  }

  /** Path part for operation `deleteParishioner()` */
  static readonly DeleteParishionerPath = '/api/parishioner/{parishionerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteParishioner()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteParishioner$Response(params: DeleteParishioner$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerDto>> {
    const obs = deleteParishioner(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteParishioner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteParishioner(params: DeleteParishioner$Params, context?: HttpContext): Observable<ParishionerDto> {
    const resp = this.deleteParishioner$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishionerDto>): ParishionerDto => r.body)
    );
  }

  /** Path part for operation `getAllParishioners()` */
  static readonly GetAllParishionersPath = '/api/parishioner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllParishioners()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishioners$Response(params?: GetAllParishioners$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishionerDto>>> {
    const obs = getAllParishioners(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllParishioners$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishioners(params?: GetAllParishioners$Params, context?: HttpContext): Observable<Array<ParishionerDto>> {
    const resp = this.getAllParishioners$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ParishionerDto>>): Array<ParishionerDto> => r.body)
    );
  }

  /** Path part for operation `createParishioner()` */
  static readonly CreateParishionerPath = '/api/parishioner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createParishioner()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createParishioner$Response(params: CreateParishioner$Params, context?: HttpContext): Observable<StrictHttpResponse<ParishionerDto>> {
    const obs = createParishioner(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createParishioner$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createParishioner(params: CreateParishioner$Params, context?: HttpContext): Observable<ParishionerDto> {
    const resp = this.createParishioner$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ParishionerDto>): ParishionerDto => r.body)
    );
  }

  /** Path part for operation `getAllParishionersSummary()` */
  static readonly GetAllParishionersSummaryPath = '/api/parishioner/summary';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllParishionersSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishionersSummary$Response(params?: GetAllParishionersSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParishionerSummaryDto>>> {
    const obs = getAllParishionersSummary(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllParishionersSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllParishionersSummary(params?: GetAllParishionersSummary$Params, context?: HttpContext): Observable<Array<ParishionerSummaryDto>> {
    const resp = this.getAllParishionersSummary$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ParishionerSummaryDto>>): Array<ParishionerSummaryDto> => r.body)
    );
  }

}
