/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createPriest } from '../fn/priest/create-priest';
import { CreatePriest$Params } from '../fn/priest/create-priest';
import { deletePriest } from '../fn/priest/delete-priest';
import { DeletePriest$Params } from '../fn/priest/delete-priest';
import { getAllPriests } from '../fn/priest/get-all-priests';
import { GetAllPriests$Params } from '../fn/priest/get-all-priests';
import { getAllPriestsSummary } from '../fn/priest/get-all-priests-summary';
import { GetAllPriestsSummary$Params } from '../fn/priest/get-all-priests-summary';
import { getPriestById } from '../fn/priest/get-priest-by-id';
import { GetPriestById$Params } from '../fn/priest/get-priest-by-id';
import { PriestDto } from '../models/priest-dto';
import { PriestSummaryDto } from '../models/priest-summary-dto';
import { updatePriest } from '../fn/priest/update-priest';
import { UpdatePriest$Params } from '../fn/priest/update-priest';

@Injectable({ providedIn: 'root' })
export class PriestService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPriestById()` */
  static readonly GetPriestByIdPath = '/api/priest/{priestId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPriestById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPriestById$Response(params: GetPriestById$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestDto>> {
    const obs = getPriestById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPriestById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPriestById(params: GetPriestById$Params, context?: HttpContext): Observable<PriestDto> {
    const resp = this.getPriestById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PriestDto>): PriestDto => r.body)
    );
  }

  /** Path part for operation `updatePriest()` */
  static readonly UpdatePriestPath = '/api/priest/{priestId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePriest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePriest$Response(params: UpdatePriest$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestDto>> {
    const obs = updatePriest(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePriest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePriest(params: UpdatePriest$Params, context?: HttpContext): Observable<PriestDto> {
    const resp = this.updatePriest$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PriestDto>): PriestDto => r.body)
    );
  }

  /** Path part for operation `deletePriest()` */
  static readonly DeletePriestPath = '/api/priest/{priestId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletePriest()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePriest$Response(params: DeletePriest$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestDto>> {
    const obs = deletePriest(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletePriest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePriest(params: DeletePriest$Params, context?: HttpContext): Observable<PriestDto> {
    const resp = this.deletePriest$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PriestDto>): PriestDto => r.body)
    );
  }

  /** Path part for operation `getAllPriests()` */
  static readonly GetAllPriestsPath = '/api/priest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPriests()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPriests$Response(params?: GetAllPriests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PriestDto>>> {
    const obs = getAllPriests(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPriests$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPriests(params?: GetAllPriests$Params, context?: HttpContext): Observable<Array<PriestDto>> {
    const resp = this.getAllPriests$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<PriestDto>>): Array<PriestDto> => r.body)
    );
  }

  /** Path part for operation `createPriest()` */
  static readonly CreatePriestPath = '/api/priest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPriest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPriest$Response(params: CreatePriest$Params, context?: HttpContext): Observable<StrictHttpResponse<PriestDto>> {
    const obs = createPriest(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPriest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPriest(params: CreatePriest$Params, context?: HttpContext): Observable<PriestDto> {
    const resp = this.createPriest$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PriestDto>): PriestDto => r.body)
    );
  }

  /** Path part for operation `getAllPriestsSummary()` */
  static readonly GetAllPriestsSummaryPath = '/api/priest/summary';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPriestsSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPriestsSummary$Response(params?: GetAllPriestsSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PriestSummaryDto>>> {
    const obs = getAllPriestsSummary(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPriestsSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPriestsSummary(params?: GetAllPriestsSummary$Params, context?: HttpContext): Observable<Array<PriestSummaryDto>> {
    const resp = this.getAllPriestsSummary$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<PriestSummaryDto>>): Array<PriestSummaryDto> => r.body)
    );
  }

}
