/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AddParishionerCommand } from './models/add-parishioner-command';
export type { AddParishionerEmbeddedCommand } from './models/add-parishioner-embedded-command';
export type { AddPriestCommand } from './models/add-priest-command';
export type { AddPriestEmbeddedCommand } from './models/add-priest-embedded-command';
export type { AllTestOutputDto } from './models/all-test-output-dto';
export type { CreateParishCommand } from './models/create-parish-command';
export type { CreateParishionerCommand } from './models/create-parishioner-command';
export type { CreatePriestCommand } from './models/create-priest-command';
export type { DeleteTestOutputDto } from './models/delete-test-output-dto';
export type { ParishDocumentDto } from './models/parish-document-dto';
export type { ParishDto } from './models/parish-dto';
export type { ParishionerDto } from './models/parishioner-dto';
export type { ParishionerEmbeddedDto } from './models/parishioner-embedded-dto';
export type { ParishionerSummaryDto } from './models/parishioner-summary-dto';
export type { ParishSummaryDto } from './models/parish-summary-dto';
export type { PriestDto } from './models/priest-dto';
export type { PriestEmbeddedDto } from './models/priest-embedded-dto';
export type { PriestSummaryDto } from './models/priest-summary-dto';
export type { ReadTestOutputDto } from './models/read-test-output-dto';
export type { UpdateParishCommand } from './models/update-parish-command';
export type { UpdateParishionerCommand } from './models/update-parishioner-command';
export type { UpdateParishionerEmbeddedCommand } from './models/update-parishioner-embedded-command';
export type { UpdatePriestCommand } from './models/update-priest-command';
export type { UpdatePriestEmbeddedCommand } from './models/update-priest-embedded-command';
export type { UpdateTestOutputDto } from './models/update-test-output-dto';
export type { WriteTestOutputDto } from './models/write-test-output-dto';
