/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { PriestService } from './services/priest.service';
export { ParishionerService } from './services/parishioner.service';
export { ParishDocumentService } from './services/parish-document.service';
export { ParishService } from './services/parish.service';
export { BenchmarkService } from './services/benchmark.service';
